version: '3.1'
services:
  stats-server:
    build: stats-server/stat-service
    image: stats-server
    container_name: stats-server
    depends_on:
      - stat-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stats-db
      - POSTGRES_USER=stats-db
      - POSTGRES_PASSWORD=1234

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    depends_on:
      - main-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=main-db
      - SPRING_DATASOURCE_PASSWORD=1234

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234