version: '3.1'
services:
  stat-server:
    build: stat-server/stats-service
    image: stat-server
    container_name: stat-server
    depends_on:
      - stat-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  main-service:
    build: main-service
    image: main-service
    container_name: main-server
    depends_on:
      - main-db
      - stat-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234